Vagrant.configure(2) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.network "private_network", ip: "10.10.10.15"
  config.vm.provision "ansible", run: "always" do |ansible|
    # ansible.verbose = "vvvv"
    ansible.limit = "all"
    ansible.playbook = "deploy.yml"
    ansible.inventory_path = "ansible/vagrant-hosts"
  end
end
